server:
  port: 8489

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

auth.provider.service:
  server:
    jwtKey: ${AUTH_PROVIDER_SERVICE_SERVER_JWTKEY:wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==}
    ttlInSeconds: ${AUTH_PROVIDER_SERVICE_SERVER_TTLINSECONDS:14400}
    testing-support.enabled: ${AUTH_PROVIDER_SERVICE_TESTING_SUPPORT_ENABLED:}
    rs256:
      enabled: ${AUTH_PROVIDER_SERVICE_SERVER_RS256_ENABLED:false}
      privateKey: ${AUTH_PROVIDER_SERVICE_SERVER_RS256_PRIVATEKEY:}
      publicKey: ${AUTH_PROVIDER_SERVICE_SERVER_RS256_PUBLICKEY:}

spring:
  application:
    name: Service Auth Provider
