apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Service Auth Provider App
name: service-auth-provider-app
home: https://github.com/hmcts/service-auth-provider-app
version: 0.0.1
maintainers:
  - name: HMCTS Platform engineering team
