apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Service Auth Provider App
name: rpe-service-auth-provider
home: https://github.com/hmcts/service-auth-provider-app
version: 0.3.117
maintainers:
  - name: HMCTS Platform engineering team
dependencies:
  - name: java
    version: 5.2.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
