java:
  applicationPort: 8489
  aadIdentityName: rpe
  keyVaults:
    "s2s":
      secrets:
      - name: jwt-key
        alias: JWTKEY
      - name: app-insights-connection-string
        alias: app-insights-connection-string
      - name: microservicekey-ccd-admin
        alias: microserviceKeys.ccd_admin
      - name: microservicekey-ccd-case-document-am-api
        alias: microserviceKeys.ccd_case_document_am_api
      - name: microservicekey-am-role-assignment-service
        alias: microserviceKeys.am_role_assignment_service
      - name: microservicekey-am-role-assignment-refresh-batch
        alias: microserviceKeys.am_role_assignment_refresh_batch
      - name: microservicekey-am-judicial-booking-service
        alias: microserviceKeys.am_judicial_booking_service
      - name: microservicekey-am-org-role-mapping-service
        alias: microserviceKeys.am_org_role_mapping_service
      - name: microservicekey-ccd-case-disposer
        alias: microserviceKeys.ccd_case_disposer
      - name: microservicekey-ccd-data
        alias: microserviceKeys.ccd_data
      - name: microservicekey-ccd-definition
        alias: microserviceKeys.ccd_definition
      - name: microservicekey-ccd-definition-designer
        alias: microserviceKeys.ccd_definition_designer
      - name: microservicekey-ccd-gw
        alias: microserviceKeys.ccd_gw
      - name: microservicekey-ccd-ps
        alias: microserviceKeys.ccd_ps
      - name: microservicekey-cmc
        alias: microserviceKeys.cmc
      - name: microservicekey-cmcLegalFrontend
        alias: microserviceKeys.cmc_legal_frontend
      - name: microservicekey-cmcClaimStore
        alias: microserviceKeys.cmc_claim_store
      - name: microservicekey-cmc-claim-external-api
        alias: microserviceKeys.cmc_claim_external_api
      - name: microservicekey-divorce
        alias: microserviceKeys.drivorce
      - name: microservicekey-divorce-frontend
        alias: microserviceKeys.divorce_frontend
      - name: microservicekey-divorceCcdSubmission
        alias: microserviceKeys.divorce_ccd_submission
      - name: microservicekey-divorceCcdValidation
        alias: microserviceKeys.divorce_ccd_validation
      - name: microservicekey-divorceDocumentUpload
        alias: microserviceKeys.divorce_document_upload
      - name: microservicekey-divorceDocumentGenerator
        alias: microserviceKeys.divorce_document_generator
      - name: microservicekey-draftStoreTests
        alias: microserviceKeys.draft_store_tests
      - name: microservicekey-platformJobScheduler
        alias: microserviceKeys.jobscheduler
      - name: microservicekey-reference
        alias: microserviceKeys.reference
      - name: microservicekey-sscs
        alias: microserviceKeys.sscs
      - name: microservicekey-sscs-bulkscan
        alias: microserviceKeys.sscs_bulkscan
      - name: microservicekey-sscs-tribunals-case
        alias: microserviceKeys.sscs_tribunals_case
      - name: microservicekey-probate-frontend
        alias: microserviceKeys.probate_frontend
      - name: microservicekey-probate-backend
        alias: microserviceKeys.probate_backend
      - name: microservicekey-send-letter-consumer
        alias: microserviceKeys.send_letter_consumer
      - name: microservicekey-send-letter-tests
        alias: microserviceKeys.send_letter_tests
      - name: microservicekey-em-gw
        alias: microserviceKeys.em_gw
      - name: microservicekey-finrem-document-generator
        alias: microserviceKeys.finrem_document_generator
      - name: microservicekey-finrem-notification-service
        alias: microserviceKeys.finrem_notification_service
      - name: microservicekey-finrem-case-orchestration
        alias: microserviceKeys.finrem_case_orchestration
      - name: microservicekey-finrem-payment-service
        alias: microserviceKeys.finrem_payment_service
      - name: microservicekey-finrem-ccd-data-migrator
        alias: microserviceKeys.finrem_ccd_data_migrator
      - name: microservicekey-jui-webapp
        alias: microserviceKeys.jui_webapp
      - name: microservicekey-pui-webapp
        alias: microserviceKeys.pui_webapp
      - name: microservicekey-coh-cor
        alias: microserviceKeys.coh_cor
      - name: microservicekey-bulk-scan-processor
        alias: microserviceKeys.bulk_scan_processor
      - name: microservicekey-bulk-scan-processor-tests
        alias: microserviceKeys.bulk_scan_processor_tests
      - name: microservicekey-bulk-scan-orchestrator
        alias: microserviceKeys.bulk_scan_orchestrator
      - name: microservicekey-bulk-scan-payment-processor
        alias: microserviceKeys.bulk_scan_payment_processor
      - name: microservicekey-bulk-scan-ccd-sample-app
        alias: microserviceKeys.bulk_scan_ccd_sample_app
      - name: microservicekey-bulk-scan-sample-app-tests
        alias: microserviceKeys.bulk_scan_sample_app_tests
      - name: microservicekey-reform-scan-notification-tests
        alias: microserviceKeys.reform_scan_notification_tests
      - name: microserviceKey-reform-scan-blob-router
        alias: microserviceKeys.reform_scan_blob_router
      - name: microservicekey-bar-api
        alias: microserviceKeys.bar_api
      - name: microservicekey-api-gw
        alias: microserviceKeys.api_gw
      - name: microservicekey-em-annotation-app
        alias: microserviceKeys.em_annotation_app
      - name: microservicekey-em-npa-app
        alias: microserviceKeys.em_npa_app
      - name: microservicekey-cet
        alias: microserviceKeys.cet
      - name: microservicekey-cet-frontend
        alias: microserviceKeys.cet_frontend
      - name: microservicekey-fpl-case-service
        alias: microserviceKeys.fpl_case_service
      - name: microservicekey-prl-dgs-api
        alias: microserviceKeys.prl_dgs_api
      - name: microservicekey-iac
        alias: microserviceKeys.iac
      - name: microservicekey-idam-api
        alias: microserviceKeys.idam_api
      - name: microservicekey-em-stitching-api
        alias: microserviceKeys.em_stitching_api
      - name: microservicekey-em-ccd-orchestrator
        alias: microserviceKeys.em_ccd_orchestrator
      - name: microservicekey-ccpay-bubble
        alias: microserviceKeys.ccpay_bubble
      - name: microservicekey-dg-template-management
        alias: microserviceKeys.dg_template_management_api
      - name: microservicekey-dg-docassembly-api
        alias: microserviceKeys.dg_docassembly_api
      - name: microservicekey-rd-professional-api
        alias: microserviceKeys.rd_professional_api
      - name: microservicekey-rd-user-profile-api
        alias: microserviceKeys.rd_user_profile_api
      - name: microservicekey-rd-caseworker-ref-api
        alias: microserviceKeys.rd_caseworker_ref_api
      - name: microservicekey-rd-profile-sync
        alias: microserviceKeys.rd_profile_sync
      - name: microservicekey-ethos-repl-service
        alias: microserviceKeys.ethos_repl_service
      - name: microservicekey-ecm-consumer
        alias: microserviceKeys.ecm_consumer
      - name: microservicekey-employment-tribunals
        alias: microserviceKeys.employment_tribunals
      - name: microservicekey-am-accessmgmt-api
        alias: microserviceKeys.am_accessmgmt_api
      - name: microservicekey-xui-webapp
        alias: microserviceKeys.xui_webapp
      - name: microservicekey-ctsc-work-allocation
        alias: microserviceKeys.ctsc_work_allocation
      - name: microservicekey-rd-judicial-api
        alias: microserviceKeys.rd_judicial_api
      - name: microservicekey-adoption-backend
        alias: microserviceKeys.adoption_backend
      - name: microservicekey-payment-app
        alias: microserviceKeys.payment_app
      - name: microservicekey-pcq-consolidation-service
        alias: microserviceKeys.pcq_consolidation_service
      - name: microservicekey-lau-case-backend
        alias: microserviceKeys.lau_case_backend
      - name: microservicekey-lau-frontend
        alias: microserviceKeys.lau_frontend
      - name: microservicekey-aac-manage-case-assignment
        alias: microserviceKeys.aac_manage_case_assignment
      - name: microservicekey-civil-service
        alias: microserviceKeys.civil_service
      - name: microservicekey-civil-general-applications
        alias: microserviceKeys.civil_general_applications
      - name: microservicekey-rd-location-ref-data-load
        alias: microserviceKeys.rd_location_ref_data_load
      - name: microservicekey-wa-camunda-pipeline-upload
        alias: microserviceKeys.wa_camunda_pipeline_upload
      - name: microservicekey-wa-workflow-api
        alias: microserviceKeys.wa_workflow_api
      - name: microservicekey-wa-task-management-api
        alias: microserviceKeys.wa_task_management_api
      - name: microservicekey-wa-task-configuration-api
        alias: microserviceKeys.wa_task_configuration_api
      - name: microservicekey-wa-task-monitor
        alias: microserviceKeys.wa_task_monitor
      - name: microservicekey-wa-case-event-handler
        alias: microserviceKeys.wa_case_event_handler
      - name: microservicekey-camunda-bpm
        alias: microserviceKeys.camunda_bpm
      - name: microservicekey-rd-location-ref-api
        alias: microserviceKeys.rd_location_ref_api
      - name: microservicekey-nfdiv-cms
        alias: microserviceKeys.nfdiv_cms
      - name: microservicekey-nfdiv-cos
        alias: microserviceKeys.nfdiv_cos
      - name: microservicekey-nfdiv-case-api
        alias: microserviceKeys.nfdiv_case_api
      - name: microservicekey-sptribs-case-api
        alias: microserviceKeys.sptribs_case_api
      - name: microservicekey-sptribs-dss-backend
        alias: microserviceKeys.sptribs_dss_backend
      - name: microservicekey-sptribs-frontend
        alias: microserviceKeys.sptribs_frontend
      - name: microservicekey-em-hrs-api
        alias: microserviceKeys.em_hrs_api
      - name: microservicekey-em-hrs-ingestor
        alias: microserviceKeys.em_hrs_ingestor
      - name: microservicekey-refunds-api
        alias: microserviceKeys.refunds_api
      - name: microservicekey-ccpay-cpo-function-node
        alias: microserviceKeys.ccpay_cpo_function_node
      - name: microservicekey-paymentoutcome-web
        alias: microserviceKeys.paymentoutcome_web
      - name: microservicekey-service-request-cpo-update-service
        alias: microserviceKeys.service_request_cpo_update_service
      - name: microservicekey-prl-cos-api
        alias: microserviceKeys.prl_cos_api
      - name: microservicekey-rd-commondata-api
        alias: microserviceKeys.rd_commondata_api
      - name: microservicekey-adoption-web
        alias: microserviceKeys.adoption_web
      - name: microservicekey-adoption-cos-api
        alias: microserviceKeys.adoption_cos_api
      - name: microservicekey-et-cos
        alias: microserviceKeys.et_cos
      - name: microservicekey-et-msg-handler
        alias: microserviceKeys.et_msg_handler
      - name: microservicekey-notifications-service
        alias: microserviceKeys.notifications_service
      - name: microservicekey-sscs-hearings-api
        alias: microserviceKeys.sscs_hearings_api
      - name: microservicekey-ds-ui
        alias: microserviceKeys.ds_ui
      - name: microservicekey-hmc-cft-hearing-service
        alias: microserviceKeys.hmc_cft_hearing_service
      - name: microservicekey-et-sya-api
        alias: microserviceKeys.et_sya_api
      - name: microservicekey-fis-bulk-scan-api
        alias: microserviceKeys.fis_bulk_scan_api
      - name: microservicekey-hmc-hmi-inbound-adapter
        alias: microserviceKeys.hmc_hmi_inbound_adapter
      - name: microservicekey-fis-cos-api
        alias: microserviceKeys.fis_cos_api
      - name: microservicekey-prl-citizen-frontend
        alias: microserviceKeys.prl_citizen_frontend
      - name: microservicekey-ts-translation-service
        alias: microserviceKeys.ts-translation-service
      - name: microservicekey-ccd-next-hearing-date-updater
        alias: microserviceKeys.ccd_next_hearing_date_updater
      - name: microservicekey-fis-hmc-api
        alias: microserviceKeys.fis_hmc_api
      - name: microservicekey-cui-ra
        alias: microserviceKeys.cui_ra
      - name: microservicekey-cui
        alias: microserviceKeys.civil_citizen_ui
      - name: microservicekey-civil-sdt
        alias: microserviceKeys.civil_sdt
      - name: microservicekey-disposer-idam-user
        alias: microserviceKeys.disposer-idam-user
      - name: microservicekey-disposer-fee-and-pay
        alias: microserviceKeys.disposer-fee-and-pay
      - name: microservicekey-et-hearings-api
        alias: microserviceKeys.et_hearings_api
      - name: microservicekey-idam-user-profile-bridge
        alias: microserviceKeys.idam-user-profile-bridge
      - name: microservicekey-sptribs-dss-update-case-web
        alias: microserviceKeys.sptribs_dss_update_case_web
      - name: microservicekey-pcs-api
        alias: microserviceKeys.pcs_api
      - name: microservicekey-pcs-frontend
        alias: microserviceKeys.pcs_frontend
      - name: microservicekey-civil-rtl-export
        alias: microserviceKeys.civil_rtl_export
  image: 'hmctspublic.azurecr.io/rpe/service-auth-provider:latest'
  ingressHost: rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
